application: google.com:sketch-material
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /data
  static_dir: data
  secure: always

- url: /assets
  static_dir: assets
  secure: always

- url: /scripts
  static_dir: scripts
  secure: always

- url: /images
  static_dir: images
  secure: always

- url: /styles
  static_dir: styles
  secure: always

- url: /
  static_files: index.html
  upload: index.html

- url: /help
  static_files: help.html
  upload: help.html

- url: /contact
  static_files: contact.html
  upload: contact.html

- url: /(.*\.(gif|png|jpg|mp4|webm))$
  static_files: static/\1
  upload: static/.*\.(gif|png|jpg|mp4|webm)$

- url: /.*
  script: main.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

skip_files:
# Default patterns skipped by App Engine, which must be repeated since
# specifying skip_files overrides them otherwise.  See
# https://developers.google.com/appengine/docs/python/config/appconfig#Skipping_Files.
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
# Build files that have no effect in App Engine's runtime.
- ^.*\.MF$
- ^.*\.CMF$
- ^.*\.so$
- ^.*pywrap.+\.py$
- ^.*\.jslib$
